# Myntra India Marketplace — Data Cleaning & Normalisation

In [19]:
!pip install pandas numpy openpyxl sqlalchemy pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (1.26.4)
Requirement already satisfied: openpyxl in c:\programdata\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: pymysql in c:\users\janvipriyanshi\appdata\roaming\python\python312\site-packages (1.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: et-xmlfile in c:\programdata\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

# Import libraries

In [21]:
import pandas as pd
import numpy as np
import os
print('Libraries loaded successfully!')

Libraries loaded successfully!

# Load the Excel file

In [23]:
os.chdir(r"C:\Users\JANVIPRIYANSHI\OneDrive\Desktop\myntra_folder")   # update your path
print(os.listdir())

['Myntra_Case_Study_2023_2025.pdf', 'Myntra_dataset_.xlsx', 'myntra_normalised']

In [24]:
df = pd.read_excel('Myntra_dataset_.xlsx', sheet_name='Myntra_Sales_Data')
print(df.shape)
df.head()

(4500, 28)

,Order_ID,Product_ID,Date,Month,Year,Quarter,Brand,Category,Sub_Category,Product_Color,...,Return_Amount,Net_Sales_Amount,Customer_ID,Customer_City,Customer_State,Payment_Method,Delivery_Partner,Customer_Segment,Customer_Rating,Delivery_Days
0,MYN0000001,PRD821797,2023-01-01,January,2023,Q1,Van Heusen,Accessories,Scarves,Red,...,0,7074,BAN_REG_0001,Bangalore,Karnataka,EMI,DTDC,Regular,4,9
1,MYN0000002,PRD679651,2023-01-01,January,2023,Q1,Van Heusen,Sportswear,Sports Shoes,Blue,...,0,5712,IND_NEW_0001,Indore,Madhya Pradesh,Credit Card,BlueDart,New Customer,4,9
2,MYN0000003,PRD536132,2023-01-01,January,2023,Q1,H&M,Sportswear,Sports Bra,Grey,...,10360,0,CHE_VIP_0001,Chennai,Tamil Nadu,EMI,FedEx,VIP,3,6
3,MYN0000004,PRD946559,2023-01-02,January,2023,Q1,Biba,Kidswear,Kids Shoes,Red,...,5499,0,KOL_PRE_0001,Kolkata,West Bengal,Net Banking,DTDC,Premium,1,8
4,MYN0000005,PRD878826,2023-01-02,January,2023,Q1,Van Heusen,Winterwear,Hoodies,Maroon,...,1086,0,CHA_PRE_0001,Chandigarh,Punjab,Myntra Pay,Ecom Express,Premium,1,6

# Check data types and nulls

In [26]:
df.dtypes

Order_ID                      object
Product_ID                    object
Date                  datetime64[ns]
Month                         object
Year                           int64
Quarter                       object
Brand                         object
Category                      object
Sub_Category                  object
Product_Color                 object
MRP                            int64
Discount_%                     int64
Selling_Price                  int64
Quantity                       int64
Gross_Sales_Amount             int64
Is_Returned                     bool
Return_Date           datetime64[ns]
Return_Reason                 object
Return_Amount                  int64
Net_Sales_Amount               int64
Customer_ID                   object
Customer_City                 object
Customer_State                object
Payment_Method                object
Delivery_Partner              object
Customer_Segment              object
Customer_Rating                int64
Delivery_Days                  int64
dtype: object

In [27]:
df.isnull().sum()

Order_ID                 0
Product_ID               0
Date                     0
Month                    0
Year                     0
Quarter                  0
Brand                    0
Category                 0
Sub_Category             0
Product_Color            0
MRP                      0
Discount_%               0
Selling_Price            0
Quantity                 0
Gross_Sales_Amount       0
Is_Returned              0
Return_Date           3712
Return_Reason         3712
Return_Amount            0
Net_Sales_Amount         0
Customer_ID              0
Customer_City            0
Customer_State           0
Payment_Method           0
Delivery_Partner         0
Customer_Segment         0
Customer_Rating          0
Delivery_Days            0
dtype: int64

In [28]:
df.duplicated().sum()

0

# Rename column & fix dates

In [30]:
df = df.rename(columns={'Discount_%': 'Discount_Pct'})

In [31]:
df['Date']        = pd.to_datetime(df['Date'],        errors='coerce')
df['Return_Date'] = pd.to_datetime(df['Return_Date'], errors='coerce')

# Fill Return_Reason nulls

In [33]:
# Nulls are valid — non-returned orders have no return info
df['Return_Reason'] = df['Return_Reason'].fillna('No Return')
df['Return_Reason'].value_counts()

Return_Reason
No Return             3712
Size Issue             122
Wrong Product          120
Defective/Damaged      118
Not as Described       112
Fit Issue              110
Changed Mind           106
Better Price Found     100
Name: count, dtype: int64

# Re-derive time columns from Date

In [35]:
df['Month']   = df['Date'].dt.month_name()
df['Year']    = df['Date'].dt.year
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df[['Date','Month','Year','Quarter']].head(3)

        Date    Month  Year Quarter
0 2023-01-01  January  2023      Q1
1 2023-01-01  January  2023      Q1
2 2023-01-01  January  2023      Q1

# Validate financial columns

In [37]:
df['Gross_Sales_Amount'] = df['Selling_Price'] * df['Quantity']
df['Net_Sales_Amount']   = df['Gross_Sales_Amount'] - df['Return_Amount']

print('Selling_Price > MRP:', (df['Selling_Price'] > df['MRP']).sum())

Selling_Price > MRP: 0

# Standardise string columns

In [39]:
str_cols = ['Brand','Category','Sub_Category','Product_Color',
            'Customer_City','Customer_State','Payment_Method',
            'Delivery_Partner','Customer_Segment','Return_Reason']

for col in str_cols:
    df[col] = df[col].astype(str).str.strip().str.title()

df['Order_ID']   = df['Order_ID'].str.strip().str.upper()
df['Product_ID'] = df['Product_ID'].str.strip().str.upper()
print('Done!')

Done!

# Add Discount_Band and City_Tier

In [41]:
bins   = [0, 20, 35, 50, 70]
labels = ['Low (<=20%)', 'Mid (21-35%)', 'High (36-50%)', 'Deep (51-70%)']
df['Discount_Band'] = pd.cut(df['Discount_Pct'], bins=bins, labels=labels, include_lowest=True)
df['Discount_Band'].value_counts()

Discount_Band
High (36-50%)    1744
Low (<=20%)      1157
Mid (21-35%)      937
Deep (51-70%)     662
Name: count, dtype: int64

In [42]:
tier1 = {'Mumbai','Delhi','Bangalore','Chennai','Hyderabad','Kolkata','Pune'}
df['City_Tier'] = df['Customer_City'].apply(lambda c: 'Tier-1' if c in tier1 else 'Tier-2')
df['City_Tier'].value_counts()

City_Tier
Tier-2    2435
Tier-1    2065
Name: count, dtype: int64

# Normalisation — split into 4 tables

In [44]:
dim_product = (
    df[['Product_ID','Brand','Category','Sub_Category','Product_Color','MRP']]
    .drop_duplicates(subset=['Product_ID'])
    .reset_index(drop=True)
)
print('dim_product:', dim_product.shape)
dim_product.head()

dim_product: (4488, 6)

  Product_ID       Brand     Category  Sub_Category Product_Color   MRP
0  PRD821797  Van Heusen  Accessories       Scarves           Red  3930
1  PRD679651  Van Heusen   Sportswear  Sports Shoes          Blue  9520
2  PRD536132         H&M   Sportswear    Sports Bra          Grey  7400
3  PRD946559        Biba     Kidswear    Kids Shoes           Red  6110
4  PRD878826  Van Heusen   Winterwear       Hoodies        Maroon  1810

In [45]:
df['Product_ID'].nunique()

4488

In [46]:
dim_customer = (
    df[['Customer_ID','Customer_City','Customer_State','Customer_Segment','City_Tier']]
    .drop_duplicates(subset=['Customer_ID'])
    .rename(columns={
        'Customer_City':'City',
        'Customer_State':'State',
        'Customer_Segment':'Segment'
    })
    .reset_index(drop=True)
)

In [47]:
print('dim_customer:', dim_customer.shape)
dim_customer.head()

dim_customer: (4500, 5)

    Customer_ID        City           State       Segment City_Tier
0  BAN_REG_0001   Bangalore       Karnataka       Regular    Tier-1
1  IND_NEW_0001      Indore  Madhya Pradesh  New Customer    Tier-2
2  CHE_VIP_0001     Chennai      Tamil Nadu           Vip    Tier-1
3  KOL_PRE_0001     Kolkata     West Bengal       Premium    Tier-1
4  CHA_PRE_0001  Chandigarh          Punjab       Premium    Tier-2

In [48]:
fact_sales = df[[
    'Order_ID','Product_ID',
    'Date','Month','Year','Quarter',
    'Discount_Pct','Discount_Band',
    'Selling_Price','Quantity',
    'Gross_Sales_Amount','Net_Sales_Amount',
    'Payment_Method','Delivery_Partner',
    'Delivery_Days','Customer_Rating',
    'Is_Returned'
]].copy()

print('fact_sales:', fact_sales.shape)
fact_sales.head()

fact_sales: (4500, 17)

,Order_ID,Product_ID,Date,Month,Year,Quarter,Discount_Pct,Discount_Band,Selling_Price,Quantity,Gross_Sales_Amount,Net_Sales_Amount,Payment_Method,Delivery_Partner,Delivery_Days,Customer_Rating,Is_Returned
0,MYN0000001,PRD821797,2023-01-01,January,2023,Q1,40,High (36-50%),2358,3,7074,7074,Emi,Dtdc,9,4,False
1,MYN0000002,PRD679651,2023-01-01,January,2023,Q1,40,High (36-50%),5712,1,5712,5712,Credit Card,Bluedart,9,4,False
2,MYN0000003,PRD536132,2023-01-01,January,2023,Q1,30,Mid (21-35%),5180,2,10360,0,Emi,Fedex,6,3,True
3,MYN0000004,PRD946559,2023-01-02,January,2023,Q1,10,Low (<=20%),5499,1,5499,0,Net Banking,Dtdc,8,1,True
4,MYN0000005,PRD878826,2023-01-02,January,2023,Q1,40,High (36-50%),1086,1,1086,0,Myntra Pay,Ecom Express,6,1,True

In [49]:
print(df.columns)

Index(['Order_ID', 'Product_ID', 'Date', 'Month', 'Year', 'Quarter', 'Brand',
       'Category', 'Sub_Category', 'Product_Color', 'MRP', 'Discount_Pct',
       'Selling_Price', 'Quantity', 'Gross_Sales_Amount', 'Is_Returned',
       'Return_Date', 'Return_Reason', 'Return_Amount', 'Net_Sales_Amount',
       'Customer_ID', 'Customer_City', 'Customer_State', 'Payment_Method',
       'Delivery_Partner', 'Customer_Segment', 'Customer_Rating',
       'Delivery_Days', 'Discount_Band', 'City_Tier'],
      dtype='object')

In [50]:
fact_returns = df[df['Is_Returned'] == True][[
    'Order_ID','Product_ID',
    'Is_Returned','Return_Date','Return_Reason','Return_Amount'
]].copy()

print('fact_returns:', fact_returns.shape)
fact_returns.head()

fact_returns: (788, 6)

,Order_ID,Product_ID,Is_Returned,Return_Date,Return_Reason,Return_Amount
2,MYN0000003,PRD536132,True,2023-01-11,Size Issue,10360
3,MYN0000004,PRD946559,True,2023-01-06,Fit Issue,5499
4,MYN0000005,PRD878826,True,2023-01-10,Fit Issue,1086
14,MYN0000015,PRD405500,True,2023-01-10,Wrong Product,1236
22,MYN0000023,PRD469645,True,2023-01-21,Fit Issue,1252

In [51]:
fact_returns

,Order_ID,Product_ID,Is_Returned,Return_Date,Return_Reason,Return_Amount
2,MYN0000003,PRD536132,True,2023-01-11,Size Issue,10360
3,MYN0000004,PRD946559,True,2023-01-06,Fit Issue,5499
4,MYN0000005,PRD878826,True,2023-01-10,Fit Issue,1086
14,MYN0000015,PRD405500,True,2023-01-10,Wrong Product,1236
22,MYN0000023,PRD469645,True,2023-01-21,Fit Issue,1252
...,...,...,...,...,...,...
4470,MYN0004471,PRD384247,True,2025-12-27,Size Issue,7280
4472,MYN0004473,PRD332567,True,2025-12-28,Changed Mind,1624
4481,MYN0004482,PRD154321,True,2026-01-07,Changed Mind,2922
4489,MYN0004490,PRD857819,True,2026-01-01,Wrong Product,3462
4492,MYN0004493,PRD991207,True,2026-01-12,Defective/Damaged,4060

# Final check — is the data clean?

In [53]:
print('Shape:', df.shape)
print('\nData types:')
print(df.dtypes)
print('\nNull values:')
print(df.isnull().sum())

Shape: (4500, 30)

Data types:
Order_ID                      object
Product_ID                    object
Date                  datetime64[ns]
Month                         object
Year                           int32
Quarter                       object
Brand                         object
Category                      object
Sub_Category                  object
Product_Color                 object
MRP                            int64
Discount_Pct                   int64
Selling_Price                  int64
Quantity                       int64
Gross_Sales_Amount             int64
Is_Returned                     bool
Return_Date           datetime64[ns]
Return_Reason                 object
Return_Amount                  int64
Net_Sales_Amount               int64
Customer_ID                   object
Customer_City                 object
Customer_State                object
Payment_Method                object
Delivery_Partner              object
Customer_Segment              object
Customer_Rating                int64
Delivery_Days                  int64
Discount_Band               category
City_Tier                     object
dtype: object

Null values:
Order_ID                 0
Product_ID               0
Date                     0
Month                    0
Year                     0
Quarter                  0
Brand                    0
Category                 0
Sub_Category             0
Product_Color            0
MRP                      0
Discount_Pct             0
Selling_Price            0
Quantity                 0
Gross_Sales_Amount       0
Is_Returned              0
Return_Date           3712
Return_Reason            0
Return_Amount            0
Net_Sales_Amount         0
Customer_ID              0
Customer_City            0
Customer_State           0
Payment_Method           0
Delivery_Partner         0
Customer_Segment         0
Customer_Rating          0
Delivery_Days            0
Discount_Band            0
City_Tier                0
dtype: int64

In [54]:
orphans  = set(fact_sales['Product_ID']) - set(dim_product['Product_ID'])
mismatch = set(fact_sales['Order_ID']).symmetric_difference(set(fact_returns['Order_ID']))
print('Orphan Product_IDs :', len(orphans))
print('Order_ID mismatch  :', len(mismatch))

Orphan Product_IDs : 0
Order_ID mismatch  : 3712

# Save to CSV (needed for SQL later)

In [56]:
os.makedirs('myntra_normalised', exist_ok=True)

dim_product.to_csv('myntra_normalised/dim_product.csv',   index=False)
dim_customer.to_csv('myntra_normalised/dim_customer.csv', index=False)
fact_sales.to_csv('myntra_normalised/fact_sales.csv',     index=False)
fact_returns.to_csv('myntra_normalised/fact_returns.csv', index=False)
df.to_csv('myntra_normalised/clean_master.csv',           index=False)

print('Saved!')
print('  dim_product.csv   ->', len(dim_product),  'rows')
print('  dim_customer.csv  ->', len(dim_customer), 'rows')
print('  fact_sales.csv    ->', len(fact_sales),   'rows')
print('  fact_returns.csv  ->', len(fact_returns), 'rows')
print('  clean_master.csv  ->', len(df),           'rows')

Saved!
  dim_product.csv   -> 4488 rows
  dim_customer.csv  -> 4500 rows
  fact_sales.csv    -> 4500 rows
  fact_returns.csv  -> 788 rows
  clean_master.csv  -> 4500 rows

# Push Tables Directly Into MySQL

In [58]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:YOUR_PASSWORD@localhost:3306/your_database"
)
MYSQL_USER     = 'root'
MYSQL_PASSWORD = 'your_password'
MYSQL_HOST     = 'localhost'
MYSQL_PORT     = '3306'
MYSQL_DB       = 'Myntra_database'

engine = create_engine(
    f'mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}:{MYSQL_PORT}/{MYSQL_DB}'
)

In [59]:
tables = {
    'dim_product'  : dim_product,
    'dim_customer' : dim_customer,
    'fact_sales'   : fact_sales,
    'fact_returns' : fact_returns,
}

for name, dataframe in tables.items():
    dataframe.to_sql(name=name, con=engine, if_exists='replace', index=False, chunksize=500)
    print(f'Pushed {name:15s} — {len(dataframe):,} rows')

print('\nAll tables sent to MySQL successfully!')

Pushed dim_product     — 4,488 rows
Pushed dim_customer    — 4,500 rows
Pushed fact_sales      — 4,500 rows
Pushed fact_returns    — 788 rows

All tables sent to MySQL successfully!

In [63]:
from sqlalchemy import text

with engine.connect() as conn:
    for t in ['dim_product','dim_customer','fact_sales','fact_returns']:
        count = conn.execute(text(f'SELECT COUNT(*) FROM {t}')).fetchone()[0]
        print(f'{t:20s} -> {count:,} rows')

dim_product          -> 4,488 rows
dim_customer         -> 4,500 rows
fact_sales           -> 4,500 rows
fact_returns         -> 788 rows